#!/usr/bin/env ruby
# coding: utf-8

#This ensures Bundler can find the Gemfile/gemspec
Dir.chdir(File.expand_path(File.dirname(__FILE__))) do
    require 'bundler/setup'
    require 'syrup'
end

Syrup::Config.read("java")

